# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trasure',
            new_name='Treasure',
        ),
    ]
